#SPDX-License-Identifier: MIT-0
---
# tasks file for apache2
- name: Install apache2
  apt:
    name:
       - apache2
       - docker.io
       - unzip
       
    state: present
    update_cache: true 
- name: Start apache2 service
  service:
     name: apache2
      
     state: restarted
     enabled: true
- name: Start docker service
  service:
     name: docker

     state: started
     enabled: true
